### ISSUE TITLE
games-emulation/qmc2 build failure: "softwareimagewidget.cpp:315:22: error: aggregate ‘QPainterPath pp’ has incomplete type and cannot be defined"

### ISSUE THREAD

**Issue by Techwolf** [jorgicio/jorgicio-gentoo-overlay#249]
Parts from the build log: 

```
x86_64-pc-linux-gnu-g++ -c -pipe -O2 -w -D_REENTRANT -fPIC -DQMC2_SDLMAME -DQMC2_VERSION=0.195 -DQMC2_SVN_REV=0 -DBUILD_OS_NAME=Linux -DBUILD_OS_RELEASE=5.7.15-zen -DBUILD_MACHINE=x86_64 -DPREFIX=/usr -DDATADIR=/usr/share -DSYSCONFDIR=/etc -DQMC2_JOYSTICK=1 -DQMC2_PHONON=0 -DQMC2_
MULTIMEDIA=1 -DQMC2_FADER_SPEED=500 -DQMC2_BROWSER_EXTRAS_ENABLED -DQMC2_BROWSER_PLUGINS_ENABLED -DQMC2_BROWSER_JAVA_ENABLED -DQMC2_BROWSER_JAVASCRIPT_ENABLED -DQMC2_YOUTUBE_ENABLED -D_REENTRANT -D_7ZIP_PPMD_SUPPORT -D_7ZIP_ST -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -
DQT_SVG_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_XMLPATTERNS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_TESTLIB_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/var/tmp/portage/games-emulation/qmc2-0.195-r2/work/qmc2"' -I. -I/usr/in
clude/SDL2 -Iqftp -Ilzma -I/usr/include/minizip -I/usr/include/qt5 -I/usr/include/qt5/QtWebKitWidgets -I/usr/include/qt5/QtWebKit -I/usr/include/qt5/QtSvg -I/usr/include/qt5/QtMultimediaWidgets -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -
I/usr/include/qt5/QtXml -I/usr/include/qt5/QtXmlPatterns -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtTest -I/usr/include/qt5/QtCore -I. -I/usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o softwareimagewidget.o softwareimagewidget.cpp

softwareimagewidget.cpp: In member function ‘bool SoftwareImageWidget::loadImage(const QString&, const QString&, bool)’:
softwareimagewidget.cpp:315:22: error: aggregate ‘QPainterPath pp’ has incomplete type and cannot be defined
  315 |         QPainterPath pp;
      |                      ^~
softwareimagewidget.cpp: In member function ‘void SoftwareImageWidget::drawCenteredImage(QPixmap*, QPainter*)’:
softwareimagewidget.cpp:450:16: error: aggregate ‘QPainterPath pp’ has incomplete type and cannot be defined
  450 |   QPainterPath pp;
      |                ^~
```

I did try "MAKEOPTS="-j1" emerge -av games-emulation/qmc2" to rule out parallel make bug.

**Comment by jorgicio** [comment]
Please, post your `emerge --info` output to check more.

**Comment by jorgicio** [comment]
UPDATE: I just rebuilt qmc2 (I had it already installed) and built without any issue.
Send your `emerge --info` in order to check your issue, please.

**Comment by jeandestouches** [comment]
Same issue after updating qt from 5.14.2 to 5.15.1 (stable)
This patch resolves the issue ->

https://github.com/archlinux/svntogit-community/blob/packages/qmc2/trunk/qmc2-qt5.15.patch

**Comment by jorgicio** [comment]
Thanks, I added an improved version of the patch which check what Qt5 version have you installed.
